repos:
  # Remove virtual environment to speed up bandit
  - repo: local
    hooks:
      - id: remove-venv
        name: Remove virtual environment
        entry: bash -c 'if [ -d "venv" ]; then echo "Removing venv directory..."; rm -rf venv; fi'
        language: system
        pass_filenames: false
        always_run: true

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]
        exclude: '^triplelens/'

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]
        exclude: '^triplelens/'

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: '^triplelens/'

  # Type checking (optional but recommended)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports]
        exclude: '^triplelens/'

  # Security checks
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       args: ["-r", "GCMicrolensing/", "-r", "tests/", "-s", "B101,B110"]
  #       exclude: '^(triplelens/|venv/|\.venv/|env/|ENV/|\.env/|\.tox/|\.nox/|\.mypy_cache/|\.git/|build/|dist/|eggs/|\.eggs/|\.pytest_cache/|\.coverage/|htmlcov/|\.cache/|\.hypothesis/|\.pyre/|__pycache__/|\.DS_Store/)$'

  # Check for merge conflicts
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
        exclude: '^triplelens/'
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  # Jupyter notebook formatting (if you have notebooks)
#   - repo: https://github.com/nbQA-dev/nbQA
#     rev: 1.7.0
#     hooks:
#       - id: nbqa-black
#         args: [--line-length=100]
#         additional_dependencies: [jupyter, matplotlib]
#       - id: nbqa-isort
#         args: [--profile=black, --line-length=100]
#         additional_dependencies: [jupyter, matplotlib]
#       - id: nbqa-flake8
#         args: [--max-line-length=100, --extend-ignore=E203,W503,F841]
#         additional_dependencies: [jupyter, matplotlib]

  # Documentation checks
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=numpy]
        exclude: '^triplelens/'

  # Check for common issues in scientific code
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
