name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      PYTHONPATH: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y ffmpeg build-essential
    - name: Install pip, wheel, and build
      run: python -m pip install --upgrade pip wheel build setuptools
    - name: Install pybind11
      run: pip install pybind11>=2.3
    - name: Build TripleLensing extension
      run: |
        cd triplelens
        python setup.py build_ext --inplace
        ls -la *.so *.pyd 2>/dev/null || echo "No extension files found"
        cd ..
    - name: Install TripleLensing directly
      run: |
        cd triplelens
        pip install -e .
        cd ..
    - name: Install package (with local TripleLensing)
      run: |
        pip install -e .[dev]
        python -c "import TripleLensing; print('TripleLensing imported successfully')" || echo "TripleLensing import failed"
    - name: Run tests
      run: pytest tests/ -v --maxfail=2 --disable-warnings
