name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for changelog generation

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip wheel build setuptools
        python -m pip install pybind11 numpy

    - name: Install package dependencies for build
      run: |
        python -m pip install -r requirements-dev.txt
        python -m pip install VBMicrolensing>=5.0.0

    - name: Install package in development mode
      run: pip install .

    - name: Update version and citation files
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        DATE=$(date +%Y-%m-%d)
        python .github/scripts/bump_version.py $VERSION $DATE
    - name: Commit version/citation updates
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add setup.py CITATION.cff README.md
        git commit -m "chore: bump version to v${GITHUB_REF_NAME#v} for release" || echo "No changes to commit"
        git push || echo "No changes to push"

    - name: Build package
      run: python -m build

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## What's Changed

          This release includes:
          - Bug fixes and improvements
          - Enhanced documentation
          - Updated dependencies

          ## Installation

          ```bash
          pip install GCMicrolensing
          ```

          ## Documentation

          See the [documentation](https://gcmicrolensing.readthedocs.io/) for usage examples.
        files: |
          dist/gcmicrolensing-${{ github.ref_name }}.tar.gz
          dist/gcmicrolensing-${{ github.ref_name }}-py3-none-any.whl

  # Publish to TestPyPI
  publish-testpypi:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip wheel build setuptools twine
        python -m pip install pybind11 numpy
        python -m pip install -r requirements-dev.txt
        python -m pip install VBMicrolensing>=5.0.0
    - name: Install package in development mode
      run: pip install .
    - name: Build package
      run: python -m build
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip-existing: true

  # Publish to PyPI
  publish-pypi:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip wheel build setuptools twine
        python -m pip install pybind11 numpy
        python -m pip install -r requirements-dev.txt
        python -m pip install VBMicrolensing>=5.0.0
    - name: Install package in development mode
      run: pip install .
    - name: Build package
      run: python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
